# Generated by Django 6.0.2 on 2026-02-16 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeout', '0003_post_like_comment_bookmark_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='link_title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='link_url',
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('event_type', models.CharField(choices=[('deadline', 'Deadline'), ('exam', 'Exam'), ('class', 'Class'), ('meeting', 'Meeting'), ('study_session', 'Study Session'), ('other', 'Other')], default='other', max_length=20)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_all_day', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Optional calendar event associated with this post', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='timeout.event'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['creator', '-start_datetime'], name='timeout_eve_creator_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_datetime'], name='timeout_eve_start_idx'),
        ),
    ]
