# Generated by Django 5.2.11 on 2026-02-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeout', '0004_remove_post_image_remove_post_link_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('focus', '🎯 Focus Mode'), ('social', '💬 Social'), ('inactive', '😶 Inactive')], default='inactive', max_length=10),
        ),
    ]
