# Generated by Django 6.0.2 on 2026-02-25 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeout', '0004_remove_post_image_remove_post_link_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(max_length=5000)),
                ('category', models.CharField(choices=[('lecture', 'Lecture'), ('todo', 'To-Do'), ('study_plan', 'Study Plan'), ('personal', 'Personal'), ('other', 'Other')], default='other', max_length=20)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, help_text='Optional calendar event linked to this note', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='timeout.event')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
                'indexes': [models.Index(fields=['owner', '-is_pinned', '-created_at'], name='timeout_note_owner_pin_idx'), models.Index(fields=['owner', 'category'], name='timeout_note_owner_cat_idx')],
            },
        ),
    ]
