# Generated by Django 5.2.11 on 2026-02-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeout', '0004_remove_post_image_remove_post_link_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allow_conflict',
            field=models.BooleanField(default=False, help_text='if true, event overlaps with others'),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence',
            field=models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20),
        ),
    ]
