# Generated by Django 5.2.11 on 2026-02-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeout', '0006_remove_user_status_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('focus', '🎯 Focus Mode'), ('social', '💬 Social'), ('inactive', '😶 Inactive')], default='inactive', max_length=10),
        ),
    ]
