# Generated by Django 5.2.11 on 2026-02-25 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeout', '0005_note'),
        ('timeout', '0007_user_status'),
    ]

    operations = [
    ]
