# Generated by Django 6.0.2 on 2026-03-02 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeout', '0010_event_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='recurrence',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=10),
        ),
    ]
