# Generated by Django 6.0.2 on 2026-03-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeout', '0015_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='linked_study_sessions',
            field=models.ManyToManyField(blank=True, limit_choices_to={'event_type': 'study_session'}, related_name='linked_deadlines', to='timeout.event'),
        ),
    ]
